version: '3.8'

services:
  php:
    container_name: book-service_app
    working_dir: "/srv/app"
    build:
      context: ./
    volumes:
      - ./app:/srv/app
    networks:
      - books_network

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/srv/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - books_network

  database:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - books_network

networks:
  books_network:
    external:
      name: books_network